// 권한 수준 정의
export enum PermissionLevel {
  NONE = 0, // 접근 불가
  READ = 1, // 읽기 전용
  WRITE = 2, // 읽기/쓰기
  MANAGE = 3, // 관리 (승인/거부 등)
  ADMIN = 4, // 관리자 (모든 권한)
}

// 권한 수준 라벨
export const PERMISSION_LABELS = {
  [PermissionLevel.NONE]: "접근 불가",
  [PermissionLevel.READ]: "읽기",
  [PermissionLevel.WRITE]: "쓰기",
  [PermissionLevel.MANAGE]: "관리",
  [PermissionLevel.ADMIN]: "관리자",
}

// 권한 수준 색상
export const PERMISSION_COLORS = {
  [PermissionLevel.NONE]: "bg-gray-100 text-gray-800",
  [PermissionLevel.READ]: "bg-blue-100 text-blue-800",
  [PermissionLevel.WRITE]: "bg-green-100 text-green-800",
  [PermissionLevel.MANAGE]: "bg-orange-100 text-orange-800",
  [PermissionLevel.ADMIN]: "bg-purple-100 text-purple-800",
}

// 기능 정의
export interface Permission {
  id: string
  name: string
  description: string
  category: string
}

// 시스템 기능 목록
export const SYSTEM_PERMISSIONS: Permission[] = [
  // 차량 관리
  { id: "vehicles.view", name: "차량 조회", description: "차량 목록 및 상세 정보 조회", category: "차량 관리" },
  { id: "vehicles.create", name: "차량 등록", description: "새 차량 등록", category: "차량 관리" },
  { id: "vehicles.edit", name: "차량 수정", description: "차량 정보 수정", category: "차량 관리" },
  { id: "vehicles.delete", name: "차량 삭제", description: "차량 정보 삭제", category: "차량 관리" },
  { id: "vehicles.approve", name: "차량 승인", description: "차량 등록/수정 승인", category: "차량 관리" },
  { id: "vehicles.export", name: "차량 내보내기", description: "차량 데이터 엑셀 내보내기", category: "차량 관리" },

  // 사용자 관리
  { id: "users.view", name: "사용자 조회", description: "사용자 목록 및 상세 정보 조회", category: "사용자 관리" },
  { id: "users.create", name: "사용자 등록", description: "새 사용자 등록", category: "사용자 관리" },
  { id: "users.edit", name: "사용자 수정", description: "사용자 정보 수정", category: "사용자 관리" },
  { id: "users.delete", name: "사용자 삭제", description: "사용자 삭제", category: "사용자 관리" },
  { id: "users.approve", name: "사용자 승인", description: "사용자 가입 승인", category: "사용자 관리" },

  // 지파 관리
  { id: "branches.view", name: "지파 조회", description: "지파 정보 조회", category: "지파 관리" },
  { id: "branches.edit", name: "지파 수정", description: "지파 정보 수정", category: "지파 관리" },
  { id: "branches.stats", name: "지파 통계", description: "지파별 통계 조회", category: "지파 관리" },

  // 일괄 관리
  { id: "bulk.edit", name: "일괄 수정", description: "차량 정보 일괄 수정", category: "일괄 관리" },
  { id: "bulk.approve", name: "일괄 승인", description: "일괄 수정 승인", category: "일괄 관리" },
  { id: "bulk.history", name: "일괄 이력", description: "일괄 수정 이력 조회", category: "일괄 관리" },

  // 공지 관리
  { id: "notices.view", name: "공지 조회", description: "공지사항 조회", category: "공지 관리" },
  { id: "notices.create", name: "공지 작성", description: "공지사항 작성", category: "공지 관리" },
  { id: "notices.edit", name: "공지 수정", description: "공지사항 수정", category: "공지 관리" },
  { id: "notices.delete", name: "공지 삭제", description: "공지사항 삭제", category: "공지 관리" },

  // 시스템 관리
  { id: "system.settings", name: "시스템 설정", description: "시스템 설정 관리", category: "시스템 관리" },
  { id: "system.permissions", name: "권한 관리", description: "사용자 권한 관리", category: "시스템 관리" },
  { id: "system.logs", name: "로그 조회", description: "시스템 로그 조회", category: "시스템 관리" },
]

// 지파별 권한 매트릭스 타입
export type BranchPermissions = {
  [branchName: string]: {
    [permissionId: string]: PermissionLevel
  }
}

// 현재 권한 설정 (기본값)
export const CURRENT_PERMISSIONS: BranchPermissions = {
  요한: {
    "vehicles.view": PermissionLevel.ADMIN,
    "vehicles.create": PermissionLevel.ADMIN,
    "vehicles.edit": PermissionLevel.ADMIN,
    "vehicles.delete": PermissionLevel.ADMIN,
    "vehicles.approve": PermissionLevel.ADMIN,
    "vehicles.export": PermissionLevel.ADMIN,
    "users.view": PermissionLevel.ADMIN,
    "users.create": PermissionLevel.ADMIN,
    "users.edit": PermissionLevel.ADMIN,
    "users.delete": PermissionLevel.ADMIN,
    "users.approve": PermissionLevel.ADMIN,
    "branches.view": PermissionLevel.ADMIN,
    "branches.edit": PermissionLevel.ADMIN,
    "branches.stats": PermissionLevel.ADMIN,
    "bulk.edit": PermissionLevel.ADMIN,
    "bulk.approve": PermissionLevel.ADMIN,
    "bulk.history": PermissionLevel.ADMIN,
    "notices.view": PermissionLevel.ADMIN,
    "notices.create": PermissionLevel.ADMIN,
    "notices.edit": PermissionLevel.ADMIN,
    "notices.delete": PermissionLevel.ADMIN,
    "system.settings": PermissionLevel.ADMIN,
    "system.permissions": PermissionLevel.ADMIN,
    "system.logs": PermissionLevel.ADMIN,
  },
  베드로: {
    "vehicles.view": PermissionLevel.WRITE,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.WRITE,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  부산야고보: {
    "vehicles.view": PermissionLevel.WRITE,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.WRITE,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  안드레: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  다대오: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  빌립: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  시몬: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  바돌로매: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  마태: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  도마: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  야고보: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
  다대: {
    "vehicles.view": PermissionLevel.READ,
    "vehicles.create": PermissionLevel.WRITE,
    "vehicles.edit": PermissionLevel.READ,
    "vehicles.delete": PermissionLevel.NONE,
    "vehicles.approve": PermissionLevel.NONE,
    "vehicles.export": PermissionLevel.READ,
    "users.view": PermissionLevel.READ,
    "users.create": PermissionLevel.NONE,
    "users.edit": PermissionLevel.NONE,
    "users.delete": PermissionLevel.NONE,
    "users.approve": PermissionLevel.NONE,
    "branches.view": PermissionLevel.READ,
    "branches.edit": PermissionLevel.NONE,
    "branches.stats": PermissionLevel.READ,
    "bulk.edit": PermissionLevel.NONE,
    "bulk.approve": PermissionLevel.NONE,
    "bulk.history": PermissionLevel.READ,
    "notices.view": PermissionLevel.READ,
    "notices.create": PermissionLevel.NONE,
    "notices.edit": PermissionLevel.NONE,
    "notices.delete": PermissionLevel.NONE,
    "system.settings": PermissionLevel.NONE,
    "system.permissions": PermissionLevel.NONE,
    "system.logs": PermissionLevel.NONE,
  },
}

// 권한 확인 유틸리티 함수
export function hasPermission(
  branchName: string,
  permissionId: string,
  requiredLevel: PermissionLevel,
  permissions: BranchPermissions = CURRENT_PERMISSIONS,
): boolean {
  const branchPermissions = permissions[branchName]
  if (!branchPermissions) return false

  const userLevel = branchPermissions[permissionId] || PermissionLevel.NONE
  return userLevel >= requiredLevel
}

// 기능 카테고리 목록
export function getPermissionCategories(): string[] {
  return Array.from(new Set(SYSTEM_PERMISSIONS.map((p) => p.category)))
}

// 카테고리별 권한 목록
export function getPermissionsByCategory(category: string): Permission[] {
  return SYSTEM_PERMISSIONS.filter((p) => p.category === category)
}
